spring: 
  profiles: 
    active: 
    -  dev  #当前使用的环境
---
content: test
server: 
  port: 6001
spring: 
  profiles: dev  #开发环境
  application: 
    name: config-server-dev
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8888/eureka/
---
content: test
server: 
  port: 6002
spring: 
  profiles: test  #测试环境
  application: 
    name: config-server-test
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka01.com:1001/eureka/
